# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sm_employees', '0002_employee_skills'),
        ('sm_skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_employees.Employee')),
                ('need_skills', models.ManyToManyField(db_table='AssignmentsSkills', to='sm_skills.Skill')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_employees.Position')),
            ],
            options={
                'db_table': 'ProjectAssignments',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'Projects',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_projects.Project'),
        ),
    ]
