# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_projects', '0002_auto_20171111_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
