# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_projects', '0003_project_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
