# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillhistory',
            name='source_type',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Training'), ('2', 'Project experience')], max_length=2),
        ),
    ]
