# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_skills', '0002_auto_20171111_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
